services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE teamwork;' -U postgres
sudo: false 
language: node_js

node_js:
  - 10.16.0
install:
  - npm install
script:
  - npm test
after_success:
  -npm run coverage
cache: 
  directories: 
    - node_modules

